### ISSUE TITLE
Show how to access information retrieved during OnAuthenticated callback

### ISSUE THREAD

**Issue by FatherFoxxy** [RockstarLabs/oauthforaspnet#11]
This would be a huge help, all of the answers I have seen on Stackoverflow and such seem overly complicated for what (to me) seems like it should be a relatively simple task. My main issue being how to access SteamId after logging in through Steam.

**Comment by jerriep** [comment]
Hi @FatherFoxxy , it is already there. If you look at the Steam provider:
http://www.oauthforaspnet.com/providers/steam/

Have a look under the heading "Retrieve user information returned from Steam"

Or are you talking about something else?

**Comment by FatherFoxxy** [comment]
I saw that, but how do I access that information like the SteamId? I've looked everywhere, but all I see are outdated or overly-complicated solutions. Unless those solutions are the only way? I'm mainly talking about things like this: http://www.jerriepelser.com/blog/get-the-twitter-profile-image-using-the-asp-net-identity he is able to access the profile image URL and I wish to do the same thing with the SteamId.

**Comment by jerriep** [comment]
@laedit Do you maybe want to chirp in here please? :)

What would be the best way for them to access the SteamId in the OnAuthenticated callback? 

In the page you helped to create for the Steam provider (http://www.oauthforaspnet.com/providers/steam/) you had the following piece of code:

```
var options = new SteamAuthenticationOptions
{
    ApplicationKey = "Your API Key",
    Provider = new OpenIDAuthenticationProvider // Steam is based on OpenID
    {
        OnAuthenticated = async context =>
        {
            // Retrieve the user's identity with info like username and steam id in Claims property
            var identity = context.Identity;
        }
    }
};
app.UseSteamAuthentication(options);
```

Your comment says `// Retrieve the user's identity with info like username and steam id in Claims property`, so how do they in fact get it at that point? I do not see a property, or a claim with that information, so I am not sure whether I am missing something?

**Comment by laedit** [comment]
I haven't got the time to test if it's still ok, but this is how I was getting it:

    var steamId = context.Identity.Claims.First().Value;

The problem was the implementation of openid by steam, which is disastrous.

**Comment by FatherFoxxy** [comment]
But where would I be able to access "context.Identity.Claims.First().Value;", I can't seem to find anything in Login.aspx or RegisterExternalLogins.aspx

**Comment by laedit** [comment]
In Startup.Auth.cs:

    var options = new SteamAuthenticationOptions
    {
        ApplicationKey = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
        Provider = new OpenIDAuthenticationProvider // Steam is based on OpenID
        {
            OnAuthenticated = async context =>
            {
                // Retrieve the user's identity with info like username and steam id in Claims property
                var steamId = context.Identity.Claims.First().Value;
            }
        }
    };
    app.UseSteamAuthentication(options);

**Comment by FatherFoxxy** [comment]
Okay, you probably think I'm as dumb as all hell right now, but how would I access that data OUTSIDE of Startup.auth.cs? I attempted looking through the information in Context.GetOwinContext() but was unable to locate anything that would show me how to access that.

**Comment by jerriep** [comment]
Ahh, got it. Here is a video I made which shows you how to store claims so you can access them later on...

https://www.youtube.com/watch?v=aTEkY_E6mV8

**Comment by laedit** [comment]
Excellent video!
It could be useful to add a link to it in the oauthforaspnet website.

**Comment by jerriep** [comment]
Thank @laedit :) Yeah, I am planning to rework the oauthforaspnet website for all the new stuff coming with ASP.NET 5, and then also have a section of "general" how-tos that show all these things

**Comment by FatherFoxxy** [comment]
Wow! I wish I had found that video earlier. Thanks for all your help, I really appreciate it. Have a great day.

**Comment by jerriep** [comment]
Cool :+1:
