### ISSUE TITLE
Sample for authentication on AngularJS

### ISSUE THREAD

**Issue by mynd-paula** [RockstarLabs/oauthforaspnet#14]
Not really an issue. But do you happen to have any sample code snippets how I can use the OWIN SF authentication with AngularJS front end? The samples you have are on MVC.

We are catering to both native login, where we use OAuthAuthorizationServer an OAuthBearerAuthentication. Will it also work smoothly if we also add in using SalesforceAuthentication?

**Comment by jerriep** [comment]
The only thing I can point you to is a blog post written by @tjoudeh

http://bitoftech.net/2014/08/11/asp-net-web-api-2-external-logins-social-logins-facebook-google-angularjs-app/

**Comment by mynd-paula** [comment]
Thank you very much for your quick reply. Desperate for any solution right
now. I will try this out and I am hoping I can make it work.

On Fri, Nov 27, 2015 at 4:30 PM, Jerrie Pelser <notifications@github.com>
wrote:

> The only thing I can point you to is a blog post written by @tjoudeh
> <https://github.com/tjoudeh>
>
>
> http://bitoftech.net/2014/08/11/asp-net-web-api-2-external-logins-social-logins-facebook-google-angularjs-app/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/RockstarLabs/oauthforaspnet/issues/14#issuecomment-160068096>
> .
>



-- 
Paula Bianca Francisco
Software Developer
Mynd Dynamic Team, Inc.

Email: paula.francisco@myndconsulting.com
Skype: paula.526

**Comment by jerriep** [comment]
Pleasure :) Hope you get it solved.
