### ISSUE TITLE
facebook redirecting to http://localhost:53536/Account/Login#_=_

### ISSUE THREAD

**Issue by UdayVishwakarma** [RockstarLabs/oauthforaspnet#17]
I followed the tutorial in the below link http://www.oauthforaspnet.com/providers/facebook/guides/aspnet-mvc5/. it didnt work for me it asks for facebook permissions and redirects to http://localhost:53536/Account/Login#_=_.
 
Can someone please help me in this

**Comment by jerriep** [comment]
Please ask support questions on StackOverflow
