### ISSUE TITLE
Session is not saved - Consent screen always shown

### ISSUE THREAD

**Issue by JerrySantana** [RockstarLabs/oauthforaspnet#23]
Hi,
I have an issue, the authentication with LinkedIn in my application works fine.
My issue is the following:
1. I login with Linkedin
2. I give permissions to the application (Consent Screen)
3. Authorization is successful, everything is right so far.
4. I logout from my site (and LinkedIn).
5. I login again, the consent screen is shown again, I have permissions previously but it forces to login every time I login with LinkedIn.

I have the exactly the same example with Google, Facebook and Twitter, on these providers it only ask me once not every time I login.
In my understanding, this should be a LinkedIn issue.

Do you have some ideas?
Thanks,
Jerry.

**Comment by jerriep** [comment]
Yes, this is how LinkedIn choses to implement it. Nothing you can do about it.

BTW, in future please ask support questions on StackOverflow. Thanks!
