### ISSUE TITLE
Connecting to a locally installed WordPress

### ISSUE THREAD

**Issue by PhilippeDevaux** [RockstarLabs/oauthforaspnet#24]
Hi,

We have a locally installed wordpress site; I tried to use the connector but it seems that it can only use the online wordpress site. 

I tried to look in the WordPressAuthenticationOptions to look for a property to give the Url of my local wordpress site for authentication (using the OAuth Server that is installed in the WordPress site); but I cannot find it.

Is this possible and how ?

**Comment by jerriep** [comment]
Please ask support questions on StackOverflow. Thank you
