### ISSUE TITLE
/Account/ExternalLoginCallback?error=access_denied

### ISSUE THREAD

**Issue by vaibhavpingle** [RockstarLabs/oauthforaspnet#25]
i have been getting this error when using the salesforce provider. I have created my mvc application exactly as mentioned and my connected app setup is also on the similar lines. I am being redirected to the login, however, after login at Salesforce when it calls into signin-salesforce, it then redirects me to /Account/ExternalLoginCallback?error=access_denied. I am not able to get past this. can someone help?

**Comment by jerriep** [comment]
Please ask support questions on StackOverflow. Thanks

**Comment by vaibhavpingle** [comment]
I have posted this on stackoverflow. Any help would be great.
