### ISSUE TITLE
LinkedIn Oauth Api failing due to unannounced changes

### ISSUE THREAD

**Issue by kingkeamo** [RockstarLabs/oauthforaspnet#6]
LinkedIn made a change to their api and caused the their oauth to fail.

The fix for the issue is to set the expect100Continue header parameter to false.

In my testing I put the following setting in the web.config and is fixed the issue.

 <system.net>
    <settings>
      <servicePointManager expect100Continue="false"/>
    </settings>
  </system.net>

If project owners are ok with this fix I can add it to this repo

**Comment by jerriep** [comment]
You are in the wrong repo. You should be in https://github.com/RockstarLabs/OwinOAuthProviders

And also, the issue has already been fixed. Just grab the prerelease version of the package from Nuget.
